#ifndef CMAKE_CONFIG_H 
#define CMAKE_CONFIG_H 

#define PREFIX "${PREFIX}"
#define PROGRAMME_DIR "${PROGRAM_DIR_PREFIX}"
#define PROGRAMME_EXECUTABLE "${PROGRAM_DIR_EXECUTABLE}"
#define QM_FILES "${TRANSLATION_DIR}"

#endif
