#ifndef CMAKE_CONFIG_H 
#define CMAKE_CONFIG.H 

#define PREFIX "${PREFIX}"
#define PROGRAMME_DIR PREFIX "${PROGRAM_DIR_PREFIX}"
#define PROGRAMME_EXECUTABLE PREFIX "${PROGRAM_DIR_EXECUTABLE}"
#define QM_FILES "${TRANSLATION_DIR}"

#endif
